### ISSUE TITLE
Screen: TypeError: integer argument expected, got float

### ISSUE THREAD

**Issue by 251** [rhempel/ev3dev-lang-python#128]
```python
>>> import ev3dev.ev3 as ev3
>>> s = ev3.Screen()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/python_ev3dev-0.6.0-py3.4.egg/ev3dev/core.py", line 2310, in __init__
    "white")
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2030, in new
    return Image()._new(core.fill(mode, size, color))
TypeError: integer argument expected, got float
```

It works with integer division in core.py:Screen
```diff
<                 (self.fix_info.line_length * 8 / self.var_info.bits_per_pixel, self.yres),
---
>                 (self.fix_info.line_length * 8 // self.var_info.bits_per_pixel, self.yres),
```

**Comment by ddemidov** [comment]
Thanks! Can you make a pull request?

**Comment by 251** [comment]
It depends on how we solve this issue. My solution is Python3 specific, because I'm not interested in 2.x. We could add new features (`from __future__ import division`) and remove many casts or add another explicit type conversion here...

**Comment by ddemidov** [comment]
Integer division `//` seems to work on python2 as well:
```
python2
Python 2.7.11 (default, Dec  6 2015, 15:43:46) 
[GCC 5.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 3 / 2
1
>>> 3 // 2
1
>>> 
```

**Comment by 251** [comment]
It was PEP238 (15 years ago for 2.2).

**Comment by ddemidov** [comment]
Why do you say your solution is python3 specific then?

**Comment by 251** [comment]
Because I'm old. ;)

**Comment by rhempel** [comment]
Will merge this weekend - thks for the fix!
