### ISSUE TITLE
Trouble Using Motor Commands - "IOError: [Errno 13]"

### ISSUE THREAD

**Issue by bcorey** [rhempel/ev3dev-lang-python#95]
So if I try to run the following program, 
```
#!/usr/bin/env python

from time import sleep
from ev3dev.auto import *
m = LargeMotor(OUTPUT_D)
assert m.connected, "Missing motor in port D"
m.run_forever()
print("Hello!")

sleep(5)
```
the ```m.run_forever()``` throws this error:
```
Traceback (most recent call last):
  File "./pytests.py", line 8, in <module>
    m.run_forever()
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 630, in run_forever
    self.command = 'run-forever'
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 238, in command
    self.set_attr_string('command', value)
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 181, in set_attr_string
    self._set_attribute(attribute, "{0}".format(value))
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 169, in _set_attribute
    self._attribute_cache.write(abspath(self._path + '/' + attribute), value)
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 91, in write
    f = self.file_handle(path)
  File "/usr/lib/python2.7/dist-packages/ev3dev/core.py", line 77, in file_handle
    f = open(path, mode, 0)
IOError: [Errno 13] Permission denied: '/sys/class/tacho-motor/motor0/command'
Exception IOError: (13, 'Permission denied', '/sys/class/tacho-motor/motor0/command') in <bound method LargeMotor.__del__ of <ev3dev.core.LargeMotor object at 0xb678c030>> ignored
```
Does anyone have any idea what's going on here? When I run ```m.commands```, ```run_forever``` is listed as a valid command. Also, when I run ```m.commands```, I get an error that looks like this after the program has finished running:
```
Exception IOError: (13, 'Permission denied', '/sys/class/tacho-motor/motor0/comm          and') in <bound method LargeMotor.__del__ of <ev3dev.core.LargeMotor object at 0          xb67aa030>> ignored
```

**Comment by ddemidov** [comment]
Your user account should belong to `ev3dev` group. Look for 'Set up a new user' here: http://www.ev3dev.org/docs/getting-started/

**Comment by bcorey** [comment]
Thanks, I'll try that.

**Comment by bcorey** [comment]
Works perfectly now, thanks for your help.
